### ISSUE TITLE
Evaluate godot-gltf-module GDNative

### ISSUE THREAD

**Issue by fire** [you-win/godot-dynamic-gltf-loader#1]
Hi, 

We have ported the Godot master module to 3.x.

Can you evaluate?
 
https://github.com/V-Sekai/godot-gltf-module/tree/gdnative

**Comment by you-win** [comment]
I can confirm that this module is no longer necessary when using [Godot 3.x, commit 2d3c0d3](https://github.com/godotengine/godot/commit/2d3c0d311c3f55fcee64bccbe4476e70134a763e). Will update the readme and archive this repo for posterity.
